# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class AccumulatedImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAccumulatedImage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AccumulatedImage()
        x.Init(buf, n + offset)
        return x

    # AccumulatedImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AccumulatedImage
    def FirstPulseTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AccumulatedImage
    def PulseTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AccumulatedImage
    def DetectorId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AccumulatedImage
    def DetectorIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # AccumulatedImage
    def DetectorIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AccumulatedImage
    def DetectionCount(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AccumulatedImage
    def DetectionCountAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # AccumulatedImage
    def DetectionCountLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AccumulatedImageStart(builder): builder.StartObject(4)
def AccumulatedImageAddFirstPulseTime(builder, firstPulseTime): builder.PrependUint64Slot(0, firstPulseTime, 0)
def AccumulatedImageAddPulseTime(builder, pulseTime): builder.PrependUint64Slot(1, pulseTime, 0)
def AccumulatedImageAddDetectorId(builder, detectorId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(detectorId), 0)
def AccumulatedImageStartDetectorIdVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AccumulatedImageAddDetectionCount(builder, detectionCount): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(detectionCount), 0)
def AccumulatedImageStartDetectionCountVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AccumulatedImageEnd(builder): return builder.EndObject()
