# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class Bool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBool(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bool()
        x.Init(buf, n + offset)
        return x

    # Bool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bool
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BoolStart(builder): builder.StartObject(1)
def BoolAddValue(builder, value): builder.PrependBoolSlot(0, value, 0)
def BoolEnd(builder): return builder.EndObject()
