# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class RunInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRunInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunInfo()
        x.Init(buf, n + offset)
        return x

    # RunInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunInfo
    def InfoTypeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RunInfo
    def InfoType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RunInfoStart(builder): builder.StartObject(2)
def RunInfoAddInfoTypeType(builder, infoTypeType): builder.PrependUint8Slot(0, infoTypeType, 0)
def RunInfoAddInfoType(builder, infoType): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(infoType), 0)
def RunInfoEnd(builder): return builder.EndObject()
