# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class RunStop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRunStop(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunStop()
        x.Init(buf, n + offset)
        return x

    # RunStop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunStop
    def StopTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RunStop
    def RunNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RunStopStart(builder): builder.StartObject(2)
def RunStopAddStopTime(builder, stopTime): builder.PrependUint64Slot(0, stopTime, 0)
def RunStopAddRunNumber(builder, runNumber): builder.PrependInt32Slot(1, runNumber, 0)
def RunStopEnd(builder): return builder.EndObject()
