# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class Obj_a(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObj_a(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Obj_a()
        x.Init(buf, n + offset)
        return x

    # Obj_a
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Obj_a
    def V(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Obj_a
    def VLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def Obj_aStart(builder): builder.StartObject(1)
def Obj_aAddV(builder, v): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)
def Obj_aStartVVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def Obj_aEnd(builder): return builder.EndObject()
