# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvDouble(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvDouble(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvDouble()
        x.Init(buf, n + offset)
        return x

    # pvDouble
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvDouble
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def pvDoubleStart(builder): builder.StartObject(1)
def pvDoubleAddV(builder, v): builder.PrependFloat64Slot(0, v, 0.0)
def pvDoubleEnd(builder): return builder.EndObject()
