# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvFloat(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvFloat()
        x.Init(buf, n + offset)
        return x

    # pvFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvFloat
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def pvFloatStart(builder): builder.StartObject(1)
def pvFloatAddV(builder, v): builder.PrependFloat32Slot(0, v, 0.0)
def pvFloatEnd(builder): return builder.EndObject()
