# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvInt(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvInt()
        x.Init(buf, n + offset)
        return x

    # pvInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvInt
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def pvIntStart(builder): builder.StartObject(1)
def pvIntAddV(builder, v): builder.PrependInt32Slot(0, v, 0)
def pvIntEnd(builder): return builder.EndObject()
