# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvLong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvLong(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvLong()
        x.Init(buf, n + offset)
        return x

    # pvLong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvLong
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def pvLongStart(builder): builder.StartObject(1)
def pvLongAddV(builder, v): builder.PrependInt64Slot(0, v, 0)
def pvLongEnd(builder): return builder.EndObject()
