# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvShort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvShort(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvShort()
        x.Init(buf, n + offset)
        return x

    # pvShort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvShort
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def pvShortStart(builder): builder.StartObject(1)
def pvShortAddV(builder, v): builder.PrependInt16Slot(0, v, 0)
def pvShortEnd(builder): return builder.EndObject()
