# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvString(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvString()
        x.Init(buf, n + offset)
        return x

    # pvString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvString
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def pvStringStart(builder): builder.StartObject(1)
def pvStringAddV(builder, v): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)
def pvStringEnd(builder): return builder.EndObject()
