# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvUByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvUByte(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvUByte()
        x.Init(buf, n + offset)
        return x

    # pvUByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvUByte
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def pvUByteStart(builder): builder.StartObject(1)
def pvUByteAddV(builder, v): builder.PrependUint8Slot(0, v, 0)
def pvUByteEnd(builder): return builder.EndObject()
