# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvUInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvUInt(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvUInt()
        x.Init(buf, n + offset)
        return x

    # pvUInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvUInt
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def pvUIntStart(builder): builder.StartObject(1)
def pvUIntAddV(builder, v): builder.PrependUint32Slot(0, v, 0)
def pvUIntEnd(builder): return builder.EndObject()
