# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f140_general

import flatbuffers

class pvULong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAspvULong(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = pvULong()
        x.Init(buf, n + offset)
        return x

    # pvULong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # pvULong
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def pvULongStart(builder): builder.StartObject(1)
def pvULongAddV(builder, v): builder.PrependUint64Slot(0, v, 0)
def pvULongEnd(builder): return builder.EndObject()
