# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f143_structure

import flatbuffers

class Obj(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObj(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Obj()
        x.Init(buf, n + offset)
        return x

    # Obj
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Obj
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ObjM import ObjM
            obj = ObjM()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Obj
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ObjStart(builder): builder.StartObject(1)
def ObjAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def ObjStartValueVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ObjEnd(builder): return builder.EndObject()
