# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f143_structure

import flatbuffers

class ObjM(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjM(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjM()
        x.Init(buf, n + offset)
        return x

    # ObjM
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjM
    def K(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ObjM
    def VType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ObjM
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ObjMStart(builder): builder.StartObject(3)
def ObjMAddK(builder, k): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(k), 0)
def ObjMAddVType(builder, vType): builder.PrependUint8Slot(1, vType, 0)
def ObjMAddV(builder, v): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)
def ObjMEnd(builder): return builder.EndObject()
